name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build SignalR Lib
        run: dotnet build --configuration Release ./src/BarySignalR.SignalR
      - name: Build Orleans Lib
        run: dotnet build --configuration Release ./src/BarySignalR.OrleansSilo
